services:
  librechat:
    container_name: ${HARBOR_CONTAINER_PREFIX}.librechat
    ports:
      - "${HARBOR_LIBRECHAT_HOST_PORT}:${HARBOR_LIBRECHAT_HOST_PORT}"
    depends_on:
      - lc-db
      - lc-rag
    image: ghcr.io/danny-avila/librechat-dev:latest
    networks:
      - harbor-network
    env_file: ./.env
    environment:
      - HOST=0.0.0.0
      - PORT=${HARBOR_LIBRECHAT_HOST_PORT}
      - MONGO_URI=mongodb://lc-db:27017/LibreChat
      - MEILI_HOST=http://lc-search:7700
      - RAG_PORT=${HARBOR_LIBRECHAT_RAG_HOST_PORT}
      - RAG_API_URL=http://lc-rag:${HARBOR_LIBRECHAT_RAG_HOST_PORT}
      - ANYSCALE_API_KEY=${HARBOR_ANYSCALE_KEY:-user_provided}
      - APIPIE_API_KEY=${HARBOR_APIPIE_KEY:-user_provided}
      - COHERE_API_KEY=${HARBOR_COHERE_KEY:-user_provided}
      - FIREWORKS_API_KEY=${HARBOR_FIREWORKS_API_KEY:-user_provided}
      - GROQ_API_KEY=${HARBOR_GROQ_KEY:-user_provided}
      - HUGGINGFACE_TOKEN=${HARBOR_HF_TOKEN:-user_provided}
      - MISTRAL_API_KEY=${HARBOR_MISTRAL_KEY:-user_provided}
      - OPENROUTER_KEY=${HARBOR_OPENROUTER_KEY:-user_provided}
      - PERPLEXITY_API_KEY=${HARBOR_PERPLEXITY_KEY:-user_provided}
      - SHUTTLEAI_API_KEY=${HARBOR_SHUTTLEAI_KEY:-user_provided}
      - TOGETHERAI_API_KEY=${HARBOR_TOGETHERAI_KEY:-user_provided}
      - ANTHROPIC_API_KEY=${HARBOR_ANTHROPIC_KEY:-user_provided}
      - BINGAI_TOKEN=${HARBOR_BINGAI_TOKEN:-user_provided}
      - GOOGLE_KEY=${HARBOR_GOOGLE_KEY:-user_provided}
      - OPENAI_API_KEY=${HARBOR_OPENAI_KEY:-user_provided}
      - ASSISTANTS_API_KEY=${HARBOR_ASSISTANTS_KEY:-user_provided}
    volumes:
      - type: bind
        source: ./librechat/.env
        target: /app/.env
      - ./librechat/librechat.yml:/app/librechat.yaml
      - ./librechat/images:/app/client/public/images
      - ./librechat/logs:/app/api/logs

  lc-db:
    container_name: ${HARBOR_CONTAINER_PREFIX}.lc-db
    image: mongo
    volumes:
      - ./librechat/data:/data/db
    command: mongod --noauth
    networks:
      - harbor-network

  lc-search:
    container_name: ${HARBOR_CONTAINER_PREFIX}.lc-search
    image: getmeili/meilisearch:v1.7.3
    environment:
      - MEILI_HOST=http://lc-search:7700
      - MEILI_NO_ANALYTICS=true
    volumes:
      - ./librechat/meili_data_v1.7:/meili_data
    networks:
      - harbor-network

  lc-vector:
    container_name: ${HARBOR_CONTAINER_PREFIX}.lc-vector
    image: ankane/pgvector:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./librechat/vectordb:/var/lib/postgresql/data
    networks:
      - harbor-network

  lc-rag:
    container_name: ${HARBOR_CONTAINER_PREFIX}.lc-rag
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest
    environment:
      - DB_HOST=lc-vector
      - RAG_PORT=${HARBOR_LIBRECHAT_RAG_HOST_PORT}
      - EMBEDDINGS_PROVIDER=ollama
      - OLLAMA_BASE_URL=${HARBOR_OLLAMA_INTERNAL_URL}
      - EMBEDDINGS_MODEL=nomic-embed-text
    depends_on:
      - lc-vector
    env_file:
      - .env
    networks:
      - harbor-network
