services:
  stt:
    image: fedirz/faster-whisper-server:${HARBOR_WHISPER_VERSION}-cpu
    container_name: ${HARBOR_CONTAINER_PREFIX}.stt
    env_file:
      - ./.env
      - ./stt/override.env
    ports:
      - ${HARBOR_WHISPER_HOST_PORT}:8000
    volumes:
      - ${HARBOR_OLLAMA_CACHE}:/root/.ollama
      - ${HARBOR_HF_CACHE}:/root/.cache/huggingface
      - ${HARBOR_LLAMACPP_CACHE}:/root/.cache/llama.cpp
      - ${HARBOR_VLLM_CACHE}:/root/.cache/vllm
    networks:
      - harbor-network
