services:
  autogpt:
    image: significantgravitas/auto-gpt
    container_name: ${HARBOR_CONTAINER_PREFIX}.autogpt
    env_file:
      - ./.env
      - ./autogpt/override.env
    ports:
      - ${HARBOR_AUTOGPT_HOST_PORT}:8000
    volumes:
      - ./autogpt/workspace:/app/auto_gpt_workspace
      - ./autogpt/data:/app/data
      - ./autogpt/logs:/app/logs