services:
  mistralrs:
    image: ghcr.io/ericlbuehler/mistral.rs:cuda-80-0.2
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]