services:
  ollama:
    container_name: ollama
    env_file: ./.env
    volumes:
      - ${HARBOR_OLLAMA_CACHE}:/root/.ollama
    pull_policy: always
    tty: true
    image: ollama/ollama:latest
    ports:
      - ${HARBOR_OLLAMA_HOST_PORT}:11434
    networks:
      - harbor-network

  webui:
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
