services:
  lmdeploy:
    image: openmmlab/lmdeploy:latest
    container_name: lmdeploy
    volumes:
      - ${HARBOR_HUGGINGFACE_CACHE}:/root/.cache/huggingface
    ports:
      - ${HARBOR_LMDEPLOY_HOST_PORT}:23333
    ipc: host
    command: lmdeploy serve api_server Weni/ZeroShot-Agents-Llama3-4.0.43-ORPO-AWQ
    networks:
      - harbor-network