services:
  ollama:
    volumes:
      - ~/.ollama:/root/.ollama
    pull_policy: always
    tty: true
    image: ollama/ollama:latest
    ports:
      - 33821:11434
    networks:
      - harbor-network

  webui:
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
