services:
  fabric:
    entrypoint:
      - "bash"
      - "/app/fabric/start_fabric.sh"
      - "-m"
      - "${HARBOR_FABRIC_MODEL}"
      - "--remoteOllamaServer"
      - "${HARBOR_OLLAMA_INTERNAL_URL}"
